sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IBonE5HXOC9ZO8h7j6GLgBmG0SFy6BywdjJI6zNlgbGjis+O6dGEX7oMq/BUlE3A5xYtShfmXnqHWDrf4HPOljA0k/HAgyP2yqllszB7L20KnXvjkgS0OH1TTUeGwEzqjeXLWDytDddfOlYoOuqPetYpyPxzGLA+4AS8bjoeptlz/M51rsuxs/5xsL6SwxeME4++AaQ1oBL4XD57OH5ne/13uE1ODbTcAadOQnxHmNbory8t5WjqxtY6jBW/I9EXgVwt/tZ6ua7AaThqyKj8uTsXId9tM6hlLdMOEBH1Z5fPBaisvg89SnwhvM9NGKiOsVRpS0EQus8iyl2eSKHkpwb5buZ2LAnd4LTUEs04lS301ogniFrZV9msH5fGJ/p2TxxuJXzH/9/LaScFOYCFIlvocUAdehZoZuiRK/n3q80oiLk74/Fdf1FlPpJ/2DCjJ2IV0hI0g7TH95+jSY4FgwVUnQpHyCgTYidy945dVUYyHJ1Nyex6HxhhNLiXvOk8xO7HY3mofsONwgG12Xq0Z71nHRBAbK8+EP753Ady2jVX9nNJgoaw+HeY8bLR1M7sggFDhWuNI5b3FKaDQTqTcVCauZijAvi3EBSgQMJKkN24k98ohHzJLn1SIMfmq2G2yX72dBQRuRgkXZw3NrkIBUj096d9JiqNcUjzmzvun4E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Deerslayer_3285
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy